name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
        working-directory: incremental-game

      - name: Build Angular project
        run: npm run build
        working-directory: incremental-game

      - name: Add android platform
        run: |
          if [ ! -d "./android" ]; then npx cap add android; fi
        working-directory: incremental-game

      - name: Sync Capacitor
        run: npx cap sync
        working-directory: incremental-game

      - name: Build debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
        working-directory: incremental-game/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: incremental-game/android/app/build/outputs/apk/debug/app-debug.apk
